application: pingissimo
version: 1
runtime: go
api_version: go1

handlers:
# Misc. files
- url: /([^\.]+.txt)
  static_files: static/\1.txt
  upload: static/([^\.]+.txt)
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: _go_app

skip_files:
# Hidden files:
- ^(.*/)?\..*$
# YAML, Python, CoffeeScript, markdown, shell:
- ^(.*/)?.*\.py[co]?$
- ^(.*/)?.*\.ya?ml$
- ^(.*/)?.*\.coffee$
- ^(.*/)?.*\.markdown$
- ^(.*/)?.*\.sh$
# Misc.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*/RCS/.*$
